version: '3.8'

services:
  db:
    image: postgres:17.4
    restart: always
    environment:
      POSTGRES_USER: fd
      POSTGRES_PASSWORD: fd
      POSTGRES_DB: food_delivery
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "fd"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    image: artanebibi/food-delivery-backend
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/food_delivery
      SPRING_DATASOURCE_USERNAME: fd
      SPRING_DATASOURCE_PASSWORD: fd

  frontend:
    image: artanebibi/food-delivery-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  pgdata:
