version: '3.8'

services:
  db:
    image: postgres:17.4
    restart: always
    environment:
      POSTGRES_USER: fd
      POSTGRES_PASSWORD: fd
      POSTGRES_DB: food_delivery
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 2346:5432

volumes:
  pgdata: