apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: devops-project
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://db:5432/food_delivery"

---

apiVersion: v1
kind: Secret
metadata:
  name: fd-secrets
  namespace: devops-project
type: Opaque
data:
  SPRING_DATASOURCE_USERNAME: ZmQ=
  SPRING_DATASOURCE_PASSWORD: ZmQ=

---

apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: devops-project
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: devops-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1

  minReadySeconds: 10

  template:
    metadata:
      labels:
        app: backend
    spec:
      initContainers:
        - name: wait-for-database
          image: busybox
          command: ['sh', '-c', 'until nc -z db 5432; do echo waiting for db; sleep 2; done;']

      containers:
        - name: backend
          image: artanebibi/food-delivery-backend:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: SPRING_DATASOURCE_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: fd-secrets
                  key: SPRING_DATASOURCE_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: fd-secrets
                  key: SPRING_DATASOURCE_PASSWORD
