apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: devops-project
data:
  POSTGRES_DB: "food_delivery"

---

apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: devops-project
type: Opaque
data:
  POSTGRES_USER: ZmQ=
  POSTGRES_PASSWORD: ZmQ=

---

apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: devops-project
spec:
  ports:
    - port: 5432
      targetPort: 5432
  clusterIP: None
  selector:
    app: postgres

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: devops-project
spec:
  serviceName: db
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:17.4
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: pg-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: pg-data
          emptyDir: {}
