apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: Service
    metadata:
      name: frontend-service
      namespace: devops-project
    spec:
      type: ClusterIP
      selector:
        app: frontend

      ports:
        - port: 3000
          targetPort: 80
          protocol: TCP

  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: frontend-deployment
      namespace: devops-project
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: frontend

      strategy:
        type: RollingUpdate
        rollingUpdate:
          maxUnavailable: 1
          maxSurge: 2

      minReadySeconds: 10

      template:
        metadata:
          labels:
            app: frontend

        spec:
          containers:
            - name: frontend-container
              image: artanebibi/food-delivery-frontend:latest
              ports:
                - containerPort: 80