apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: food-db
  namespace: devops-project
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:15
  storage:
    storageClass: local-path  # or "standard" depending on your k3d setup
    size: 1Gi

  bootstrap:
    initdb:
      database: food_delivery
      owner: fd
      secret:
        name: fd-db-secret

  superuserSecret:
    name: fd-db-secret
