name: CI – Build & Push Docker Images

on:
  push:
    branches:
      - master

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  BACKEND_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/food-delivery-backend
  FRONTEND_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/food-delivery-frontend

jobs:
  build-test-push:
    runs-on: ubuntu-latest
    outputs:
      branch_name: ${{ steps.extract_branch.outputs.branch_name }}
    services:
      db:
        image: postgres:17.4
        env:
          POSTGRES_USER: ${{ secrets.DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
          POSTGRES_DB: ${{ secrets.DB_NAME }}
        ports:
          - 2346:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract branch name
        id: extract_branch
        run: echo "branch_name=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT

      - name: Build frontend
        working-directory: food-delivery-frontend
        run: |
          npm ci
          npm run build

      - name: Make mvnw executable
        working-directory: food-delivery-backend
        run: chmod +x mvnw

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin

      - name: Build and test backend
        working-directory: food-delivery-backend
        env:
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:2346/food_delivery
          SPRING_DATASOURCE_USERNAME: ${{ secrets.DB_USER }}
          SPRING_DATASOURCE_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: ./mvnw clean package

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push backend image
        working-directory: food-delivery-backend
        run: |
          docker build -t $BACKEND_IMAGE:latest .
          docker push $BACKEND_IMAGE:latest

      - name: Build and push frontend image
        working-directory: food-delivery-frontend
        run: |
          docker build -t $FRONTEND_IMAGE:latest .
          docker push $FRONTEND_IMAGE:latest

